using System;
using System.Collections.Generic;
namespace LordWar.Economy {
    public sealed class EconomyLedger {
        readonly Dictionary<string,Person> _people; readonly Dictionary<string,Kingdom> _kingdoms;
        public EconomyLedger(Dictionary<string,Person> people,Dictionary<string,Kingdom> kingdoms){_people=people;_kingdoms=kingdoms;}
        public void ProductionTick(City c,float days,float agricultureMultiplier=1f,float miningMultiplier=1f,float loggingMultiplier=1f,float smithingMultiplier=1f,float commerceMultiplier=1f){int farmers=0,miners=0,loggers=0,smiths=0,traders=0;foreach(string id in c.PersonIds){Person p;if(!_people.TryGetValue(id,out p)||!p.Alive)continue;switch(p.Job){case JobKind.Farmer:farmers++;p.Wealth+=Math.Max(0,(int)Math.Ceiling(.35f*days));p.Experience+=Math.Max(0,(int)Math.Ceiling(.18f*days));break;case JobKind.Miner:miners++;p.Wealth+=Math.Max(0,(int)Math.Ceiling(.4f*days));p.Experience+=Math.Max(0,(int)Math.Ceiling(.22f*days));break;case JobKind.Logger:loggers++;p.Wealth+=Math.Max(0,(int)Math.Ceiling(.38f*days));p.Experience+=Math.Max(0,(int)Math.Ceiling(.18f*days));break;case JobKind.Smith:smiths++;p.Wealth+=Math.Max(0,(int)Math.Ceiling(.55f*days));p.Experience+=Math.Max(0,(int)Math.Ceiling(.25f*days));break;case JobKind.Trader:traders++;p.Wealth+=Math.Max(0,(int)Math.Ceiling((p.Merchant?2.2f:.9f)*days*Mathx.Clamp(commerceMultiplier,.7f,1.5f)));p.Experience+=Math.Max(0,(int)Math.Ceiling(.15f*days));break;case JobKind.Builder:p.Wealth+=Math.Max(0,(int)Math.Ceiling(.45f*days));p.Experience+=Math.Max(0,(int)Math.Ceiling(.2f*days));break;case JobKind.Porter:p.Wealth+=Math.Max(0,(int)Math.Ceiling(.4f*days));p.Experience+=Math.Max(0,(int)Math.Ceiling(.15f*days));break;}}c.Food+=(int)(farmers*1.6f*days*Mathx.Clamp(agricultureMultiplier,.2f,1.65f));c.Iron+=(int)(miners*.55f*days*Mathx.Clamp(miningMultiplier,.7f,1.6f));c.Stone+=(int)(miners*.45f*days*Mathx.Clamp(miningMultiplier,.7f,1.6f));c.Wood+=(int)(loggers*1.1f*days*Mathx.Clamp(loggingMultiplier,.7f,1.6f));if(smiths>0&&c.Iron>0)c.Iron-=Math.Min(c.Iron,(int)(smiths*.15f*days/Mathx.Clamp(smithingMultiplier,.75f,1.6f)));Kingdom k;if(_kingdoms.TryGetValue(c.KingdomId,out k)){int commerce=(int)(traders*.35f*days*Mathx.Clamp(commerceMultiplier,.7f,1.65f));int production=(int)((farmers+miners+loggers+smiths)*.08f*days*Mathx.Clamp((miningMultiplier+loggingMultiplier+smithingMultiplier)/3f,.75f,1.5f));k.Treasury+=commerce+production;}}
        public int MerchantTax(Person merchant,int baseTax,float investmentTaxReduction){if(merchant==null||!merchant.Merchant)return 0;float wealthMul=.5f+Math.Min(2f,merchant.Wealth/800f);return Math.Max(0,(int)Math.Round(baseTax*wealthMul*(1f-Mathx.Clamp(investmentTaxReduction,0f,.8f))));}
        public bool Pay(Kingdom k,int gold){if(k==null||gold<0||k.Treasury<gold)return false;k.Treasury-=gold;return true;}
        public void Credit(Kingdom k,int gold){if(k!=null&&gold>0)k.Treasury+=gold;}
    }
}
