using LordWar.AI;
namespace LordWar {
 public static class ChineseText {
  public static string Difficulty(AiDifficulty v){switch(v){case AiDifficulty.Easy:return "简单";case AiDifficulty.Normal:return "中等";case AiDifficulty.Hard:return "困难";default:return "噩梦";}}
  public static string Season(SeasonKind v){switch(v){case SeasonKind.Spring:return "春";case SeasonKind.Summer:return "夏";case SeasonKind.Autumn:return "秋";default:return "冬";}}
  public static string Weather(WeatherKind v){switch(v){case WeatherKind.Clear:return "晴";case WeatherKind.Rain:return "雨";case WeatherKind.Storm:return "暴雨";case WeatherKind.Snow:return "雪";case WeatherKind.Blizzard:return "大雪";case WeatherKind.Fog:return "雾";case WeatherKind.Heat:return "高温";default:return "寒冷";}}
  public static string Proposal(ProposalKind v){switch(v){case ProposalKind.Appointment:return "任命";case ProposalKind.Policy:return "政策";case ProposalKind.Construction:return "工程";case ProposalKind.MilitaryReform:return "军制改革";case ProposalKind.MerchantInvestment:return "商人投资";case ProposalKind.Diplomacy:return "外交";default:return "晋升";}}
  public static string Building(BuildingKind v){switch(v){case BuildingKind.House:return "住宅";case BuildingKind.Shop:return "商铺";case BuildingKind.Market:return "市集";case BuildingKind.Granary:return "粮仓";case BuildingKind.Barracks:return "军营";case BuildingKind.Stable:return "马厩";case BuildingKind.Workshop:return "工坊";case BuildingKind.Smithy:return "铁匠铺";case BuildingKind.Armory:return "军械库";case BuildingKind.TrainingGround:return "训练场";case BuildingKind.Road:return "道路";case BuildingKind.Bridge:return "桥梁";case BuildingKind.Wall:return "城墙";case BuildingKind.Gate:return "城门";case BuildingKind.Tower:return "塔楼";default:return "官署";}}
  public static string Zone(ZoneKind v){switch(v){case ZoneKind.Residential:return "住宅区";case ZoneKind.Commercial:return "商业区";case ZoneKind.Workshop:return "工坊区";case ZoneKind.Agriculture:return "农牧区";case ZoneKind.Military:return "军政区";default:return "公共区";}}
  public static string ArmyOrderText(ArmyOrder v){switch(v){case ArmyOrder.Hold:return "驻守";case ArmyOrder.Muster:return "集结";case ArmyOrder.March:return "行军";case ArmyOrder.Engage:return "交战";case ArmyOrder.Siege:return "围城";case ArmyOrder.Retreat:return "撤退";case ArmyOrder.PursueLimited:return "有限追击";case ArmyOrder.PursueFull:return "全面追击";case ArmyOrder.Camp:return "扎营休整";default:return "驻守";}}
  public static string PursuitModeText(PursuitMode v){switch(v){case PursuitMode.Stop:return "停止追击";case PursuitMode.Full:return "全面追击";default:return "有限追击";}}
  public static string Social(SocialClass v){switch(v){case SocialClass.Commoner:return "平民";case SocialClass.Merchant:return "商人";case SocialClass.Noble:return "贵族";case SocialClass.Official:return "官员";case SocialClass.Officer:return "军官";case SocialClass.General:return "将军";default:return "领主";}}
  public static string Job(JobKind v){switch(v){case JobKind.Farmer:return "农夫";case JobKind.Miner:return "矿工";case JobKind.Logger:return "伐木工";case JobKind.Smith:return "铁匠";case JobKind.Builder:return "工匠";case JobKind.Porter:return "运输工";case JobKind.Trader:return "商贾";case JobKind.Soldier:return "士兵";case JobKind.Officer:return "军官";case JobKind.Official:return "官员";default:return "待业";}}
  public static string Injury(InjuryState v){switch(v){case InjuryState.Light:return "轻伤";case InjuryState.Heavy:return "重伤";case InjuryState.Incapacitated:return "失去战斗能力";case InjuryState.Dead:return "阵亡";case InjuryState.Captured:return "被俘";default:return "健康";}}
  public static string EquipmentSlot(string v){if(string.IsNullOrEmpty(v))return "未指定";if(v=="MainHand"||v=="主手")return "主手";if(v=="OffHand"||v=="副手")return "副手";if(v=="Head"||v=="头部")return "头盔";if(v=="Body"||v=="身体")return "身体护甲";if(v=="Feet"||v=="脚部")return "鞋靴";if(v=="Special"||v=="特殊")return "特殊物品";return "特殊物品";}
  public static string Diplomacy(DiplomacyState v){switch(v){case DiplomacyState.Trade:return "通商";case DiplomacyState.NonAggression:return "互不侵犯";case DiplomacyState.Alliance:return "同盟";case DiplomacyState.War:return "战争";case DiplomacyState.Vassal:return "附庸";default:return "中立";}}
  public static string KingdomStatusText(KingdomStatus v){switch(v){case KingdomStatus.Vassal:return "附庸";case KingdomStatus.Eliminated:return "灭亡";default:return "正常";}}
  public static string WarFocus(WarAdministrationFocus v){switch(v){case WarAdministrationFocus.Defense:return "守城";case WarAdministrationFocus.FieldBattle:return "野战";case WarAdministrationFocus.Siege:return "攻城";case WarAdministrationFocus.Interception:return "拦截";default:return "综合战务";}}
  public static string Morale(MoraleState x){switch(x){case MoraleState.Exalted:return "高昂";case MoraleState.Steady:return "稳定";case MoraleState.Shaken:return "动摇";case MoraleState.Breaking:return "濒临崩溃";case MoraleState.Routed:return "溃败";default:return "稳定";}}
 }
}
