using System;
using System.Collections.Generic;
using LordWar.Simulation;
using LordWar.AI;
namespace LordWar.Save {
 public static class GameSaveService {
  public static GameSave Capture(GameWorld w){if(w==null)throw new ArgumentNullException("w");var s=new GameSave{SaveVersion=SaveOwner.CurrentVersion,VersionName=BuildInfo.VersionName,Seed=w.Seed,Day=w.Day,PlayerKingdomId=w.PlayerKingdomId,Map=w.Map,IdSequence=Ids.Current,SimulationTick=w.Clock.TickIndex,TickPendingSeconds=w.Clock.PendingSeconds,TimeIntoDaySeconds=w.TimeIntoDaySeconds,TimeScale=w.TimeScale,Paused=w.Paused,ComputerDifficulty=(int)w.ComputerDifficulty};s.ProcessedCommandIds.AddRange(w.ProcessedCommandIds);foreach(var x in w.Events)s.Events.Add(x);foreach(var x in w.ActiveBattles.Values)s.ActiveBattles.Add(x);foreach(var x in w.People.Values)s.People.Add(x);foreach(var x in w.Families.Values)s.Families.Add(x);foreach(var x in w.Cities.Values)s.Cities.Add(x);foreach(var x in w.Kingdoms.Values)s.Kingdoms.Add(x);foreach(var x in w.Armies.Values)s.Armies.Add(x);foreach(var x in w.Buildings.Values)s.Buildings.Add(x);foreach(var x in w.Equipment.Values)s.Equipment.Add(x);foreach(var x in w.Projects.Values)s.Projects.Add(x);foreach(var x in w.Proposals.Queue)s.Proposals.Add(x);foreach(var x in w.Battles)s.Battles.Add(x);foreach(var x in w.Diplomacy.All())s.Diplomacy.Add(x);foreach(var x in w.Merchants.Investments)s.MerchantInvestments.Add(x);if(w.WarAdministration!=null)foreach(var x in w.WarAdministration.All())s.WarAdministrations.Add(x);foreach(var x in w.Sieges.All())s.Sieges.Add(x);foreach(var x in w.Herds.Values)s.Herds.Add(x);foreach(var x in w.SupplyRoutes.Values)s.SupplyRoutes.Add(x);foreach(var x in w.SupplyConvoys.Values)s.SupplyConvoys.Add(x);return s;}
  public static bool Validate(GameSave s,out string error){
   error="";if(s==null){error="存档为空";return false;}if(s.SaveVersion>SaveOwner.CurrentVersion){error="存档版本高于当前程序";return false;}SaveOwner.Migrate(s);
   if(s.SimulationTick<0||s.TickPendingSeconds<0f||s.TickPendingSeconds>2f||s.TimeIntoDaySeconds<0f||s.TimeIntoDaySeconds>=30f){error="模拟时钟无效";return false;}
   var commandIds=new HashSet<string>();foreach(string id in s.ProcessedCommandIds)if(string.IsNullOrEmpty(id)||!commandIds.Add(id)){error="命令ID缺失或重复";return false;}
   if(s.Map==null||s.Map.Width<=0||s.Map.Height<=0||s.Map.Tiles==null||s.Map.Tiles.Length!=s.Map.Width*s.Map.Height){error="随机地图结构无效";return false;}
   if(s.Kingdoms.Count==0||s.Cities.Count==0){error="国家或城市数据为空";return false;}
   var people=new Dictionary<string,Person>();var families=new Dictionary<string,Family>();var cities=new Dictionary<string,City>();var kingdoms=new Dictionary<string,Kingdom>();var armies=new Dictionary<string,Army>();var buildings=new Dictionary<string,Building>();var equipment=new Dictionary<string,EquipmentInstance>();var projects=new Dictionary<string,ConstructionProject>();var proposals=new Dictionary<string,Proposal>();var routes=new Dictionary<string,SupplyRoute>();
   foreach(Person x in s.People){if(x==null||string.IsNullOrEmpty(x.Id)||people.ContainsKey(x.Id)){error="人物ID缺失或重复";return false;}people[x.Id]=x;}
   foreach(Family x in s.Families){if(x==null||string.IsNullOrEmpty(x.Id)||families.ContainsKey(x.Id)){error="家族ID缺失或重复";return false;}families[x.Id]=x;}
   foreach(City x in s.Cities){if(x==null||string.IsNullOrEmpty(x.Id)||cities.ContainsKey(x.Id)){error="城市ID缺失或重复";return false;}cities[x.Id]=x;}
   foreach(Kingdom x in s.Kingdoms){if(x==null||string.IsNullOrEmpty(x.Id)||kingdoms.ContainsKey(x.Id)){error="国家ID缺失或重复";return false;}kingdoms[x.Id]=x;}
   foreach(Army x in s.Armies){if(x==null||string.IsNullOrEmpty(x.Id)||armies.ContainsKey(x.Id)){error="军队ID缺失或重复";return false;}armies[x.Id]=x;}
   foreach(Building x in s.Buildings){if(x==null||string.IsNullOrEmpty(x.Id)||buildings.ContainsKey(x.Id)){error="建筑ID缺失或重复";return false;}buildings[x.Id]=x;}
   foreach(EquipmentInstance x in s.Equipment){if(x==null||string.IsNullOrEmpty(x.InstanceId)||equipment.ContainsKey(x.InstanceId)){error="装备实例ID缺失或重复";return false;}equipment[x.InstanceId]=x;}
   foreach(ConstructionProject x in s.Projects){if(x==null||string.IsNullOrEmpty(x.Id)||projects.ContainsKey(x.Id)){error="施工项目ID缺失或重复";return false;}projects[x.Id]=x;}
   foreach(Proposal x in s.Proposals){if(x==null||string.IsNullOrEmpty(x.Id)||proposals.ContainsKey(x.Id)){error="申请ID缺失或重复";return false;}proposals[x.Id]=x;}
   foreach(SupplyRoute x in s.SupplyRoutes){if(x==null||string.IsNullOrEmpty(x.Id)||routes.ContainsKey(x.Id)){error="补给路线ID缺失或重复";return false;}routes[x.Id]=x;}

   var battleSessionIds=new HashSet<string>();var battlingArmies=new HashSet<string>();foreach(BattleSession session in s.ActiveBattles){if(session==null||string.IsNullOrEmpty(session.Id)||!battleSessionIds.Add(session.Id)){error="持续战斗会话ID缺失或重复";return false;}if(session.Completed){error="已完成战斗仍留在活动会话";return false;}if(!armies.ContainsKey(session.AttackerArmyId)||!armies.ContainsKey(session.DefenderArmyId)||session.AttackerArmyId==session.DefenderArmyId){error="持续战斗军队引用无效";return false;}if(!battlingArmies.Add(session.AttackerArmyId)||!battlingArmies.Add(session.DefenderArmyId)){error="同一军队同时进入多场战斗";return false;}if(session.ElapsedSeconds<0||session.MaxSeconds<0||session.ElapsedSeconds>session.MaxSeconds){error="持续战斗时间状态无效";return false;}if(session.Report==null||string.IsNullOrEmpty(session.Report.Id)){error="持续战斗缺少实时战报";return false;}if(session.RandomState==0){error="持续战斗随机状态无效";return false;}if(!string.IsNullOrEmpty(session.Report.LastActorId)&&!people.ContainsKey(session.Report.LastActorId)){error="持续战斗攻击者引用无效";return false;}if(!string.IsNullOrEmpty(session.Report.LastTargetId)&&!people.ContainsKey(session.Report.LastTargetId)){error="持续战斗防御者引用无效";return false;}if(!string.IsNullOrEmpty(session.SiegeCityId)&&!cities.ContainsKey(session.SiegeCityId)){error="破城战城市引用无效";return false;}}

   if(!string.IsNullOrEmpty(s.PlayerKingdomId)&&!kingdoms.ContainsKey(s.PlayerKingdomId)){error="玩家国家引用无效";return false;}
   foreach(Kingdom k in s.Kingdoms){
    if(k.Status!=KingdomStatus.Eliminated){if(string.IsNullOrEmpty(k.CapitalCityId)||!cities.ContainsKey(k.CapitalCityId)){error="存续国家缺少有效都城："+k.Id;return false;}if(cities[k.CapitalCityId].KingdomId!=k.Id){error="国家都城归属不一致："+k.Id;return false;}}
    if(k.Status==KingdomStatus.Vassal){if(string.IsNullOrEmpty(k.OverlordKingdomId)||!kingdoms.ContainsKey(k.OverlordKingdomId)||k.OverlordKingdomId==k.Id){error="附庸宗主引用无效："+k.Id;return false;}}
    foreach(string cid in k.CityIds){City c;if(!cities.TryGetValue(cid,out c)||c.KingdomId!=k.Id){error="国家城市列表引用无效："+k.Id;return false;}}
    foreach(string aid in k.ArmyIds){Army a;if(!armies.TryGetValue(aid,out a)||a.KingdomId!=k.Id){error="国家军队列表引用无效："+k.Id;return false;}}
   }
   foreach(City c in s.Cities){if(!kingdoms.ContainsKey(c.KingdomId)){error="城市引用不存在国家："+c.Id;return false;}if(c.X<0||c.Y<0||c.X>=s.Map.Width||c.Y>=s.Map.Height){error="城市坐标越界："+c.Id;return false;}if(!string.IsNullOrEmpty(c.PreviousKingdomId)&&!kingdoms.ContainsKey(c.PreviousKingdomId)){error="占领前国家引用无效："+c.Id;return false;}if(c.Occupation==OccupationPolicy.Pending&&(c.LastCapturedDay<0||string.IsNullOrEmpty(c.PreviousKingdomId))){error="待处置占领状态缺少攻占历史："+c.Id;return false;}foreach(string pid in c.PersonIds)if(!people.ContainsKey(pid)){error="城市人物引用无效："+c.Id;return false;}foreach(string bid in c.BuildingIds){Building b;if(!buildings.TryGetValue(bid,out b)||b.CityId!=c.Id){error="城市建筑引用无效："+c.Id;return false;}}foreach(string fid in c.FamilyIds){Family f;if(!families.TryGetValue(fid,out f)||f.HomeCityId!=c.Id&&f.MemberIds.Count==0){error="城市家族引用无效："+c.Id;return false;}}}
   var zoneIds=new HashSet<string>();foreach(City c in s.Cities){if(c.Zones==null){error="城市规划区列表为空："+c.Id;return false;}foreach(CityZone z in c.Zones){if(z==null||string.IsNullOrEmpty(z.Id)||!zoneIds.Add(z.Id)){error="城市规划区ID缺失或重复："+c.Id;return false;}if(z.CityId!=c.Id){error="城市规划区归属不一致："+z.Id;return false;}if(z.CenterX<0||z.CenterY<0||z.CenterX>=s.Map.Width||z.CenterY>=s.Map.Height||z.Radius<2||z.Radius>6){error="城市规划区坐标或半径无效："+z.Id;return false;}}}
   foreach(Family f in s.Families){if(!string.IsNullOrEmpty(f.HomeCityId)&&!cities.ContainsKey(f.HomeCityId)){error="家族所属城市引用无效："+f.Id;return false;}foreach(string pid in f.MemberIds){Person p;if(!people.TryGetValue(pid,out p)||p.FamilyId!=f.Id){error="家族成员引用不一致："+f.Id;return false;}}foreach(string aid in f.AllyFamilyIds)if(!families.ContainsKey(aid)){error="家族盟友引用无效："+f.Id;return false;}foreach(string rid in f.RivalFamilyIds)if(!families.ContainsKey(rid)){error="家族宿敌引用无效："+f.Id;return false;}}

   var activePersonnel=new Dictionary<string,string>();
   foreach(Army a in s.Armies){
    if(!kingdoms.ContainsKey(a.KingdomId)){error="军队国家引用无效："+a.Id;return false;}if(a.X<0||a.Y<0||a.X>=s.Map.Width||a.Y>=s.Map.Height){error="军队坐标越界："+a.Id;return false;}
    if(!string.IsNullOrEmpty(a.GeneralId)){Person g;if(!people.TryGetValue(a.GeneralId,out g)){error="军队主将引用无效："+a.Id;return false;}if(activePersonnel.ContainsKey(g.Id)){error="人物重复进入多个军队编制："+g.Id;return false;}activePersonnel[g.Id]=a.Id;}
    foreach(string gid in a.SubGeneralIds){if(!people.ContainsKey(gid)){error="副将引用无效："+a.Id;return false;}if(activePersonnel.ContainsKey(gid)){error="人物重复进入多个军队编制："+gid;return false;}activePersonnel[gid]=a.Id;}
    foreach(Squad q in a.Squads){if(q==null||string.IsNullOrEmpty(q.Id)){error="军队存在无效部伍："+a.Id;return false;}if(q.ArmyId!=a.Id){error="部伍所属军队不一致："+q.Id;return false;}if(!string.IsNullOrEmpty(q.OfficerId)){if(!people.ContainsKey(q.OfficerId)){error="军官引用无效："+q.Id;return false;}if(activePersonnel.ContainsKey(q.OfficerId)){error="人物重复进入多个军队编制："+q.OfficerId;return false;}activePersonnel[q.OfficerId]=a.Id;}foreach(string pid in q.SoldierIds){Person soldier;if(!people.TryGetValue(pid,out soldier)){error="士兵引用无效："+q.Id;return false;}if(activePersonnel.ContainsKey(pid)){error="人物重复进入多个军队编制："+pid;return false;}activePersonnel[pid]=a.Id;if(!soldier.Alive||soldier.Injury==InjuryState.Dead||soldier.Injury==InjuryState.Captured){error="阵亡/被俘人物仍在现役部伍："+pid;return false;}}}
   }
   foreach(Person p in s.People){if(!string.IsNullOrEmpty(p.KingdomId)&&!kingdoms.ContainsKey(p.KingdomId)){error="人物国家引用无效："+p.Id;return false;}if(!string.IsNullOrEmpty(p.CityId)&&!cities.ContainsKey(p.CityId)){error="人物城市引用无效："+p.Id;return false;}if(!string.IsNullOrEmpty(p.FamilyId)&&!families.ContainsKey(p.FamilyId)){error="人物家族引用无效："+p.Id;return false;}if(p.IsWorldWalker&&(p.WalkRoute==null||p.WalkRoute.Count<2||p.WalkRouteIndex<0||p.WalkRouteIndex>=p.WalkRoute.Count||p.X!=p.WalkRoute[p.WalkRouteIndex].X||p.Y!=p.WalkRoute[p.WalkRouteIndex].Y)){error="行走人物路径无效："+p.Id;return false;}if(p.Injury==InjuryState.Captured&&!string.IsNullOrEmpty(p.CapturedByKingdomId)&&!kingdoms.ContainsKey(p.CapturedByKingdomId)){error="俘虏引用不存在国家："+p.Id;return false;}foreach(string eid in p.EquipmentIds){EquipmentInstance e;if(!equipment.TryGetValue(eid,out e)||e.OwnerId!=p.Id){error="人物装备引用不一致："+p.Id;return false;}}}
   foreach(EquipmentInstance e in s.Equipment){if(!string.IsNullOrEmpty(e.OwnerId)&&!people.ContainsKey(e.OwnerId)){error="装备持有人引用无效："+e.InstanceId;return false;}if(e.Durability<0||e.MaxDurability<=0||e.Durability>e.MaxDurability){error="装备耐久数据无效："+e.InstanceId;return false;}}
   foreach(Building b in s.Buildings)if(!cities.ContainsKey(b.CityId)){error="建筑城市引用无效："+b.Id;return false;}
   foreach(ConstructionProject cp in s.Projects){if(!cities.ContainsKey(cp.CityId)){error="施工城市引用无效："+cp.Id;return false;}if(!string.IsNullOrEmpty(cp.ProposalId)&&!proposals.ContainsKey(cp.ProposalId)){error="施工申请引用无效："+cp.Id;return false;}if(cp.IsRepair&&!string.IsNullOrEmpty(cp.TargetBuildingId)&&!buildings.ContainsKey(cp.TargetBuildingId)){error="维修建筑引用无效："+cp.Id;return false;}}
   foreach(MerchantInvestment inv in s.MerchantInvestments){if(inv==null||string.IsNullOrEmpty(inv.Id)||!people.ContainsKey(inv.MerchantId)||!people.ContainsKey(inv.GeneralId)){error="商人投资引用无效";return false;}}
   var warAdminIds=new HashSet<string>();var warAdminPairs=new HashSet<string>();var warOfficials=new HashSet<string>();foreach(WarAdministration wa in s.WarAdministrations){if(wa==null||string.IsNullOrEmpty(wa.Id)||!warAdminIds.Add(wa.Id)){error="战争行政ID缺失或重复";return false;}if(!kingdoms.ContainsKey(wa.KingdomId)||!kingdoms.ContainsKey(wa.EnemyKingdomId)||wa.KingdomId==wa.EnemyKingdomId){error="战争行政国家引用无效";return false;}string pair=wa.KingdomId+">"+wa.EnemyKingdomId;if(!warAdminPairs.Add(pair)){error="同一战争存在多个战争行政Owner记录";return false;}Person official;if(!people.TryGetValue(wa.OfficialId,out official)||official.KingdomId!=wa.KingdomId||official.Class!=SocialClass.Official||official.Job!=JobKind.Official){error="战争负责官员引用无效";return false;}if(!warOfficials.Add(wa.KingdomId+">"+wa.OfficialId)){error="同一官员同时负责多场战争";return false;}}
   foreach(DiplomacyRelation r in s.Diplomacy){if(r==null||!kingdoms.ContainsKey(r.A)||!kingdoms.ContainsKey(r.B)||r.A==r.B){error="外交关系引用无效";return false;}if(r.State==DiplomacyState.Vassal&&(string.IsNullOrEmpty(r.SuzerainId)||string.IsNullOrEmpty(r.VassalId)||!kingdoms.ContainsKey(r.SuzerainId)||!kingdoms.ContainsKey(r.VassalId))){error="附庸外交方向引用无效";return false;}}
   foreach(SiegeState sg in s.Sieges){if(sg==null||!cities.ContainsKey(sg.CityId)||!armies.ContainsKey(sg.AttackerArmyId)){error="围城引用无效";return false;}}
   foreach(SupplyRoute r in s.SupplyRoutes){if(!armies.ContainsKey(r.ArmyId)||!cities.ContainsKey(r.SourceCityId)){error="补给路线引用无效";return false;}}
   foreach(SupplyConvoy c in s.SupplyConvoys){if(c==null||!armies.ContainsKey(c.ArmyId)||!cities.ContainsKey(c.SourceCityId)||!routes.ContainsKey(c.RouteId)){error="运输队引用无效";return false;}}
   return true;
  }
  public static void Restore(GameWorld w,GameSave s){if(w==null||s==null)throw new ArgumentNullException();string error;if(!Validate(s,out error))throw new InvalidOperationException("存档校验失败："+error);Ids.RestoreToAtLeast(s.IdSequence);w.Seed=s.Seed;w.Day=s.Day;w.ComputerDifficulty=(AiDifficulty)Math.Max(0,Math.Min(3,s.ComputerDifficulty));w.Map=s.Map;w.People.Clear();foreach(var x in s.People)w.People[x.Id]=x;w.Families.Clear();foreach(var x in s.Families)w.Families[x.Id]=x;w.Cities.Clear();foreach(var x in s.Cities)w.Cities[x.Id]=x;w.Kingdoms.Clear();foreach(var x in s.Kingdoms)w.Kingdoms[x.Id]=x;w.Armies.Clear();foreach(var x in s.Armies)w.Armies[x.Id]=x;w.Buildings.Clear();foreach(var x in s.Buildings)w.Buildings[x.Id]=x;w.Equipment.Clear();foreach(var x in s.Equipment){if(string.IsNullOrEmpty(x.DisplayName)){LordWar.Data.EquipmentTypeDef d;if(w.Data!=null&&w.Data.EquipmentTypes.TryGetValue(x.TemplateId,out d))x.DisplayName=d.Name;else x.DisplayName="未知装备";}w.Equipment[x.InstanceId]=x;}w.Projects.Clear();foreach(var x in s.Projects)w.Projects[x.Id]=x;w.Herds.Clear();foreach(var x in s.Herds)w.Herds[x.Id]=x;w.SupplyRoutes.Clear();foreach(var x in s.SupplyRoutes)w.SupplyRoutes[x.Id]=x;w.SupplyConvoys.Clear();foreach(var x in s.SupplyConvoys)w.SupplyConvoys[x.Id]=x;w.Battles.Clear();w.Battles.AddRange(s.Battles);w.Events.Clear();w.Events.AddRange(s.Events);w.RebindAfterLoad(s.PlayerKingdomId,s.Proposals,s.Diplomacy,s.MerchantInvestments,s.Sieges,s.SupplyRoutes,s.SupplyConvoys,s.ActiveBattles,s.WarAdministrations);w.RestoreClock(s.TimeIntoDaySeconds,s.TimeScale,s.Paused,s.SimulationTick,s.TickPendingSeconds);w.RestoreCommands(s.ProcessedCommandIds);}
 }
}
