using System;
using System.Collections.Generic;
using LordWar.Data;
namespace LordWar.Military {
 public sealed class EquipmentOwner {
  readonly Dictionary<string,EquipmentInstance> _equipment; readonly Dictionary<string,Person> _people;
  public EquipmentOwner(Dictionary<string,EquipmentInstance> equipment,Dictionary<string,Person> people){_equipment=equipment;_people=people;}
  public EquipmentInstance Create(string template,string qualityName,int quality,int atk,int def,int durability,int value,string city,string maker,bool unique){var e=new EquipmentInstance{InstanceId=Ids.Next("ITEM"),TemplateId=template,DisplayName=template,QualityName=qualityName,Quality=quality,Attack=atk,Defense=def,Durability=durability,MaxDurability=durability,BaseValue=value,OriginCityId=city,MakerId=maker,Source="军械工坊配发",Unique=unique};if(unique)e.History.Add("铸造于"+city);_equipment[e.InstanceId]=e;return e;}
  public EquipmentInstance CreateFromDefinition(EquipmentTypeDef type,EquipmentQualityDef quality,string city,string maker,string source){if(type==null||quality==null)return null;int atk=Math.Max(0,(int)Math.Round(type.Attack*quality.CombatMultiplier));int def=Math.Max(0,(int)Math.Round(type.Defense*quality.CombatMultiplier));int dur=Math.Max(1,(int)Math.Round(type.Durability*quality.DurabilityMultiplier));int value=Math.Max(1,(int)Math.Round((8+type.Attack*2+type.Defense*2+type.Durability*.08f)*quality.CostMultiplier));bool unique=quality.Level>=5;var e=new EquipmentInstance{InstanceId=Ids.Next("ITEM"),TemplateId=type.Id,DisplayName=type.Name,Slot=NormalizeSlot(type.Slot),QualityName=quality.Name,Quality=quality.Level,Attack=atk,Defense=def,Durability=dur,MaxDurability=dur,WeightKg=type.Weight,Weight=(int)Math.Round(type.Weight),Material=type.Material,BaseValue=value,OriginCityId=city,MakerId=maker,Source=string.IsNullOrEmpty(source)?"军械工坊配发":source,Unique=unique};if(unique)e.History.Add(quality.Name+"「"+type.Name+"」铸造于"+city);_equipment[e.InstanceId]=e;return e;}
  static string NormalizeSlot(string slot){if(string.IsNullOrEmpty(slot))return "特殊物品";if(slot.IndexOf("主手")>=0)return "主手";if(slot.IndexOf("副手")>=0||slot.IndexOf("盾")>=0)return "副手";if(slot.IndexOf("头")>=0||slot.IndexOf("盔")>=0)return "头盔";if(slot.IndexOf("甲")>=0||slot.IndexOf("身体")>=0)return "身体护甲";if(slot.IndexOf("靴")>=0||slot.IndexOf("鞋")>=0||slot.IndexOf("胫")>=0)return "鞋靴";return "特殊物品";}
  public bool Equip(Person p,EquipmentInstance e,string slot){if(p==null||e==null||!p.Alive)return false;slot=string.IsNullOrEmpty(slot)?e.Slot:slot;for(int i=p.EquipmentIds.Count-1;i>=0;i--){EquipmentInstance old;if(_equipment.TryGetValue(p.EquipmentIds[i],out old)&&old.Slot==slot){old.OwnerId="";p.EquipmentIds.RemoveAt(i);}}e.OwnerId=p.Id;if(string.IsNullOrEmpty(e.OriginalOwnerId))e.OriginalOwnerId=p.Id;e.Slot=slot;if(!p.EquipmentIds.Contains(e.InstanceId))p.EquipmentIds.Add(e.InstanceId);if(e.Unique)e.History.Add("配发给"+p.Name);return true;}
  public int Repair(EquipmentInstance e,MilitaryAccount account,float repairEfficiency=1f){if(e==null||account==null)return 0;float efficiency=Mathx.Clamp(repairEfficiency,.70f,1.75f);int baseCost=EquipmentDurabilitySystem.RepairCost(e,e.BaseValue);int cost=baseCost<=0?0:Math.Max(1,(int)Math.Ceiling(baseCost/efficiency));if(cost<=0)return 0;if(account.Gold<cost)return -cost;account.Gold-=cost;e.Durability=e.MaxDurability;if(e.Unique)e.History.Add("军械匠完成维修");return cost;}
  public EquipmentInstance CreateHistoric(EquipmentTypeDef type,EquipmentQualityDef quality,City city,string maker,string title){if(type==null||quality==null||city==null)return null;EquipmentInstance e=CreateFromDefinition(type,quality,city.Id,maker,"名匠独立铸造");if(e==null)return null;e.Unique=true;e.DisplayName=string.IsNullOrEmpty(title)?quality.Name+"·"+type.Name:title;e.History.Add("第一个主人尚未确定；出自"+city.Name);return e;}
  public bool TransferUnique(EquipmentInstance e,Person from,Person to,string history){if(e==null||!e.Unique||to==null)return false;if(from!=null)from.EquipmentIds.Remove(e.InstanceId);if(!to.EquipmentIds.Contains(e.InstanceId))to.EquipmentIds.Add(e.InstanceId);e.OwnerId=to.Id;e.History.Add(history);return true;}
 }
}
